### ISSUE TITLE
iPad host compatibility

### ISSUE THREAD

**Issue by joebowbeer** [gbevin/ShowMIDI#21] opened 2023-11-21 07:49 UTC
These hosts work:

* AUM
* Drambo
* miRack

These hosts have issues:

* It crashes apeMatrix
* I don't see it listed in Logic Pro - resolved: appears in MIDI FX on an existing track
* It loads in Loopy Pro but won't display (OSStatus error 10868)

iPad Pro (11-inch) (3rd generation) iPadOS 17.1.1

**Comment by gbevin** [comment] 2023-11-21 12:03
Works fine in Logic for me. It should be in the Midi FX to the left of the regular plugins.

![IMG_0202](https://github.com/gbevin/ShowMIDI/assets/701148/6678afd9-cd3b-43fc-8530-04803c926a71)
![IMG_0202](https://github.com/gbevin/ShowMIDI/assets/701148/5ae4a420-2aa7-4f8b-bcb1-1da45bc4f280)

**Comment by gbevin** [comment] 2023-11-21 12:06
Afaik I know Loopy Pro doesn't have support for pure MIDI Effects

**Comment by gbevin** [comment] 2023-11-21 12:08
I can reproduce the ApeMatrix crash, but sadly can't debug that. I would say, if the host crashes, it's a bug in the host. I try to look closer, but there's not even crashlogs to go by for me in this case.

**Comment by joebowbeer** [comment] 2023-11-21 15:48
Thanks. I'll report the apeMatrix issue to apeSoft.

As for Logic, it isn't showing for me. The only MIDI-controlled Effects listed for Uwyn is MIDI Tape Recorder, and if I uninstall that the Uwyn group goes away.

![IMG_0831](https://github.com/gbevin/ShowMIDI/assets/28679/ce9089c4-b1e1-479f-b5d0-e2e5b25aa14c)

**Comment by gbevin** [comment] 2023-11-21 15:52
Are you trying it in the MIDI FX slot in Logic?

**Comment by joebowbeer** [comment] 2023-11-21 15:55
I see it in Logic now! It is not listed in two places where MIDI Tape Recorder appears, like the one above, but it is listed in an instrument track under MIDI FX, as you wrote.

**Comment by gbevin** [comment] 2023-11-21 16:03
When released MTR I didn't make it a pure midi effect because too many hosts didn't support it yet. For ShowMIDI is felt it was time to go that route, no reason to create audio busses for no reason.

**Comment by gbevin** [comment] 2023-11-24 13:27
I'm closing this now, Loopy Pro has implemented proper support, once Apematrix does too we should be good to go. I don't think there's anything I can do about this at this point.

**Closed by gbevin** 2023-11-24 13:27 UTC
